name: 02 - Workflow Events

on:
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch: 


jobs:
    echo:
        runs-on: windows:latest
        steps:
            - name: Show the trigger
              run: echo "I've been trigged by a(n) ${{ github.event_name}} name."

            